// ptimerevent.h
// The timer event.
//
// Copyright 2012 - 2014 by Future Interface. 
// This software is licensed under the terms of the MIT license.
//
// Hongwei Li lihw81@gmail.com
//
// 

P_EVENTPARAMETER__TIMER_ID               = 0,  // pUint32
P_EVENTPARAMETER__TIMER_REPEAT_TIMES     = 1,  // pUint32
P_EVENTPARAMETER__TIMER_ELAPSED_MILLIS   = 2,  // pUint32

P_EVENTPARAMETER__TIMER_PARAMETER_FIRST = P_EVENTPARAMETER__TIMER_ID,
P_EVENTPARAMETER__TIMER_PARAMETER_LAST  = P_EVENTPARAMETER__TIMER_ELAPSED_MILLIS,

P_EVENTPARAMETER__TIMER_PARAMETER_NUMBER = P_EVENTPARAMETER__TIMER_PARAMETER_LAST - P_EVENTPARAMETER__TIMER_PARAMETER_FIRST + 1,
